(require 'regtests)

(test-is "let" (let ((a 3)
                     (b 4))
                 (let ((a b)
                       (b a))
                   (cons a b)))
         "(4 . 3)")
(test-is "let*" (let ((a 3)
                      (b 4))
                  (let* ((a b)
                         (b a))
                    (cons a b)))
         "(4 . 4)")
(test-is "flet" (flet((fac (lambda (n)
                             (flet ((fac (lambda (n acc)
                                           (if (zerop n)
                                               acc
                                             (fac (- n 1) (* n acc))))))
                               (fac n 1)))))
                  (fac 7))
         5040)

(done-testing)
