(require 'regtests)

(let ((n 4)
      (m 7.25)
      (o -123456))
  (test-form "incf 1" (lambda () (progn (incf n)
                                      n))
           "5")
  (test-form "incf 2" (lambda () (incf n)) "6")
  (test-form "incf 3" (lambda () (incf n 3)) "9")
  (test-form "incf 4" (lambda () (progn (errset (incf n 'b)
                                              nil)
                                      (car (#/:.*:/ sys:last-error))))
           ": argument is not a number:")
  (test-form "incf 5" (lambda () (incf m)) "8.25")
  (test-form "incf 6" (lambda () (incf o (- 3))) "-123459")
  (test-form "decf 1" (lambda () (progn (decf n)
                                      n))
           "8")
  (test-form "decf 2" (lambda () (decf n)) "7")
  (test-form "decf 3" (lambda () (decf n 3)) "4")
  (test-form "decf 4" (lambda () (progn (errset (decf n 'b)
                                              nil)
                                      (car (#/:.*:/ sys:last-error))))
           ": argument is not a number:")
  (test-form "decf 5" (lambda () (decf m)) "7.25")
  (test-form "decf 6" (lambda () (decf o (- 3))) "-123456")
  )

(let ((n 0))
  (test-form "incf eval form" (lambda () (incf n (+ 2 3))) 5)
  )

(done-testing)
