(require 'regtests)

(test-is "list collector 0" (let ((lc (list-collector)))
                              (lc))
         '())
(test-is "list collector 1" (let ((lc (list-collector)))
                              (lc 'the-atom)
                              (lc))
         '(the-atom))
(test-is "list collector 2" (let ((lc1 (list-collector))
                                  (lc2 (list-collector))
                                  (the-evils '(evil evil)))
                              (lc1 'see)
                              (lc2 'hear)
                              (lc1 0)
                              (lc2 "no")
                              (lc1 (car the-evils))
                              (lc2 (cadr the-evils))
                              (list (lc1) (lc2)))
         '((see 0 evil) (hear "no" evil)))
(test-is "list collector n" (let ((lc (list-collector)))
                              (lc 'see)
                              (lc 0 'evil)
                              (lc 'hear "no" 'evil)
                              (lc))
         '(see 0 evil hear "no" evil))

(done-testing)
