#!/bin/ksh
# start the lyk Lisp interpreter
#
# This script does not work with dash, bash, or zsh; reasons are
# outlined below.

# this is so lyk can determine as what it was called, the execution path
export LYK_CALLED_AS="$0"

# this is also a base for the load path
installbase=$(dirname $0)/..
installdir=$installbase/lib/lyk
export LYKPATH=${LYKPATH-.:$installdir:$HOME/devel/lyk/src}
export LYKLOADPATH=${LYKLOADPATH-.:$installbase/lib/site-lyk:$installdir/l}

if [ -t 0 ]; then
    # I know this is a crutch, as the terminal (window) size can
    # change at any time. But this is better than nothing, and with
    # "nothing" I mean Java's ability to let me catch and handle
    # SIGWINCH. Or other signals, for that matter.

    # this works only with ksh and zsh
    stty size | read LINES COLUMNS
    export LINES COLUMNS
fi

if [ "$1" = -J ]; then
    JARPATH="$2"
    shift; shift
else
    # the following does not work with zsh, which is weird
    JARPATH=
    IFS=:
    for dir in $LYKPATH; do
        if [ -f $dir/lyk.jar ]; then
            JARPATH=$dir
            break
        fi
    done
fi

if [ -z "$JARPATH" ]; then
    echo $(basename $0): "lyk.jar not found in $LYKPATH" 1>&2
    exit 2
fi

exec java -jar $JARPATH/lyk.jar "$@"
