;;; type predicates for all types known to lyk

(test "type predicate builtin"               (fboundp 'builtinp))
(test "type predicate char"                  (fboundp 'charp))
(test "type predicate cons"                  (fboundp 'consp))
(test "type predicate console-reader-stream" (fboundp 'console-reader-stream-p))
(test "type predicate environment"           (fboundp 'environmentp))
(test "type predicate error-object"          (fboundp 'error-object-p))
(test "type predicate file-io-stream"        (fboundp 'file-io-stream-p))
(test "type predicate file-reader-stream"    (fboundp 'file-reader-stream-p))
(test "type predicate file-writer-stream"    (fboundp 'file-writer-stream-p))
(test "type predicate lambda"                (fboundp 'lambdap))
(test "type predicate macro"                 (fboundp 'macrop))
(test "type predicate number"                (fboundp 'numberp))
(test "type predicate regexp"                (fboundp 'regexpp))
(test "type predicate string"                (fboundp 'stringp))
(test "type predicate string-reader-stream"  (fboundp 'string-reader-stream-p))
(test "type predicate string-writer-stream"  (fboundp 'string-writer-stream-p))
(test "type predicate symbol"                (fboundp 'symbolp))
(test "type predicate table"                 (fboundp 'tablep))
(test "type predicate vector"                (fboundp 'vectorp))
(test "type predicate function"              (fboundp 'functionp))
(test "type predicate stream"                (fboundp 'streamp))
(test "type predicate sequence"              (fboundp 'sequencep))

(done-testing)
